- name: play level variables 
  hosts: localhost
  connection: local
  vars:
    name: "Teja Destin"
    age: 22
    course: "DevOps"
  tasks:
    - name: "print the message"
      ansible.builtin.debug:
        msg: "My name is {{ name }}, I am {{ age }} years old and I am pursuing {{ course }}."