- name: varibale preference
  hosts: localhost
  connection: local
  vars:
    NAME: "ansible from playbook"
    age: 28
    course: "DevOps"

  vars_files:
    - course.yaml  

  vars_prompt:
  - name: NAME
    prompt: "Please enter your name"
    private: no

  tasks:
    - name: "print the message"
      vars:
        NAME: "ansible from task"
      ansible.builtin.debug:
        msg: "My name is {{ NAME }}"
