- name: check number leass than 10
  hosts: localhost 
  connection: local
  vars:
    NUMBER: 5 
  tasks:
    - name: check number less than 10
      ansible.builtin.debug:
        msg: "Number is less than 10"
      when: NUMBER < 10