- name: anisble command vs sell module
  hosts: localhost 
  connection: local
  tasks:
    - name: using module test
      # ansible.builtin.command: cat /etc/passwd | grep root
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: command_output

    - name: print command output
      ansible.builtin.debug:
        msg: "{{ command_output.stdout }}"

    - name: using module test
      # ansible.builtin.command: cat /etc/passwd | grep root
      ansible.builtin.shell: ls -ltr > files.txt
      register: files_output

    - name: print files output
      ansible.builtin.debug:
        msg: "{{ files_output }}"

