- name: demo for filters
  hosts: localhost 
  connection: local
  tasks: 
  - name: greetings
    ansible.builtin.debug:
    msg: "Hello, {{ GREETINGS | default('good morning') }}!" # if GREETINGS variable is not defined, it will print world