- name: demo for filters
  hosts: localhost 
  connection: local
  vars: 
    topics: ansible, devops, automation #string to list
    tagsMap: 
     name: ansible
     project: roboshop
     component: catalog  
    tagsList: 
      name: [{'key': 'name', 'value': 'ansible'}, 
         {'key': 'project', 'value': 'roboshop'}, 
         {'key': 'component', 'value': 'catalog'}
      ]

  tasks: 
  - name: greetings
    ansible.builtin.debug:
     msg: "Hello, {{ GREETINGS | default('good morning') }}!" # if GREETINGS variable is not defined, it will print world

  - name: covert string to list
    ansible.builtin.debug:
     msg: "Topics are {{ topics | split(',') }}" # split filter to convert string to list

  - name: covert map to list
    ansible.builtin.debug:
     msg: "Topics are {{ tagsMap | dict2items }}" # split filter to convert string to list and list filter to convert map to list

  - name: covert List of maps
    ansible.builtin.debug:
     msg: "Topics are {{ tagsList | items2dict }}" # split filter to convert string to list and list filter to convert map to list and map filter to convert list to map