- name: demo on error handling
  hosts: localhost 
  connection: local
  become: true

  tasks: 
  - name: check user exist or not 
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true # if the command fails, it will ignore the error and continue with the next task
  - name: print the user_output
    ansible.builtin.debug:
     msg: "{{ user_output }}"
  - name: create user if not exist
    ansible.builtin.command: useradd roboshop
    when: user_output.rc != 0 # if the return code is not 0, it means the user does not exist and it will create the user 
