- name: demo on error handling
  hosts: localhost 
  connection: local

  tasks: 
  - name: check user exist or not 
    ansible.builtin.command: id -u ansible
    register: user_output
    ignore_errors: true # if the command fails, it will ignore the error and continue with the next task
  - name: print the user_output
    ansible.builtin.debug:
     msg: "{{ user_output }}"